### ISSUE TITLE
 it doesn't work to open it  ox_target

### ISSUE THREAD

**Issue by leventepvp** [Z3rio/zerio-advent#1]
![image](https://user-images.githubusercontent.com/59410749/205664644-25b1164a-e9cf-4d4b-a767-c06865facf1a.png)

**Comment by Z3rio** [comment]
Hm, I will take a look at this.

**Comment by Z3rio** [comment]
This should now be fixed if you redownload the client files + make sure the numbers in Config.TargetSize are decimal numbers
