### ISSUE TITLE
F8 Console Issue 

### ISSUE THREAD

**Issue by chrisandkitt** [Z3rio/zerio-advent#2]
![grafik](https://github.com/Z3rio/zerio-advent/assets/139385951/16f83fea-8195-48da-90c4-552d4dfe2e88)

**Comment by XAR-dev** [comment]
Same man can't do nothing about probl something with [https://](https://zerio-advent/loaded)

**Comment by Z3rio** [comment]
Remove `-main` from the name.

**Comment by Z3rio** [comment]
I went ahead and edited the NUI callbacks, so they should now support any resource name if you redownload the HTML files.
