### ISSUE TITLE
problems with cars / duplicate entries

### ISSUE THREAD

**Issue by ElderDragon76** [Z3rio/zerio-advent#3]
Hey, first of all thanks for the great script! 
We have a problem. Cars are not correctly given. Seems the script tries to use duplicate plate entries in the database. Any ideas?

![image](https://github.com/Z3rio/zerio-advent/assets/140805813/200a3e0b-e7b6-457c-ad29-d578d673c61d)

**Comment by Z3rio** [comment]
Wow, the odds of this happening are **incredibly** low, as it generates a random plate.
So I assumed this would never happen to anyone.

I'll have a look at adding duplication checks then.

**Comment by ElderDragon76** [comment]
Looks like it works now. Thanks a lot for the awesome and mega quick respond and script improvement!
